//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RBManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Resource1 = new HashSet<Resource>();
        }
    
        public int ID { get; set; }
        public int CATID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int ACCID { get; set; }
        public int PRJID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Publish { get; set; }
        public bool Status { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual Project Project { get; set; }
        public virtual ResourceCategory ResourceCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resource> Resource1 { get; set; }
        public virtual Resource Resource2 { get; set; }
    }
}
